title: "com.jason.kslo"
title_separator: "|"
subtitle: "By Jason Leung"

remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: sunrise

markdown: GFM

include:
  - "_pages"

plugins:
  - jekyll-include-cache
